import React, { Component } from "react";
import "./App.css";
import { main } from "./output/Main";
import { contextComponent, viewComponent, Binding } from "./client/hoc";

main();

class App extends Component
{
  render ()
  {
    return (
      <div className="App">
        <header className="App-header">
          <h1 className="App-title">Perspectives editor</h1>
        </header>
        <div>
          <p>
            <button onClick={() => alert("clicked me")}>Clear</button>
          </p>
        </div>
        <Systeem instance="model:User$MijnSysteem" />
      </div>
    );
  }
}

const Systeem =
        contextComponent(
          "model:Systeem$Systeem",
          [
            "gebruiker",
            "trustedCluster"
          ],
          function ()
          {
            return (
              <div>
                <Gebruiker_VolledigeNaam instance={this.state.gebruiker[0]} />
                <Binding instance={this.state.trustedCluster[0]}>
                  <TrustedCluster_BuitenRol_Kaartje instance={this.state.binding}/>
                </Binding>
              </div>
            );
          });

const PropTypes = {};

// Boilerplate code, can be generated by Perspectives for any Rol and View.
// TODO: de propertynamen kunnen uit een aspect komen, of van de binding.
// TODO: De locale naam is dan onvoldoende.
gebruiker_VolledigeNaam.propTypes = {voornaam: PropTypes.string, achternaam: PropTypes.string};
gebruiker_VolledigeNaam.rol = "model:Systeem$Systeem$gebruiker";
const Gebruiker_VolledigeNaam = viewComponent( gebruiker_VolledigeNaam );

function gebruiker_VolledigeNaam(props)
{
  return <p><label>Gebruiker:</label>{props.voornaam + " " + props.achternaam}</p>;
}

// Boilerplate code, can be generated by Perspectives for any Rol and View.
trustedCluster_BuitenRol_Kaartje.propTypes = {naam: PropTypes.string};
trustedCluster_BuitenRol_Kaartje.rol = "model:Systeem$TrustedCluster$buitenRolBeschrijving";
const TrustedCluster_BuitenRol_Kaartje = viewComponent( trustedCluster_BuitenRol_Kaartje );

function trustedCluster_BuitenRol_Kaartje(props)
{
  return <p><label>TrustedCluster:</label>{props.naam}</p>;
}

export default App;
